function [drone,warehouse,order] = GiveOrders(drone,...
                     warehouse,...
                     order,...
                     nWarehouses,...
                     nOrders,...
                     indexFreeDrones,...
                     t,...
                     maxPayload,...
                     productWeights)
                     
  for i = indexFreeDrones
    [loadedDrone,order,warehouse] = LoadDrone(drone(i),order,warehouse,productWeights,maxPayload);
    drone(i) = loadedDrone;
  end
     
      
      
    
  end               
                   

                   
                   
                   